/* eslint-disable */
// GENERATED by scripts/gen-namespaces.mjs — DO NOT EDIT.
// Stripe-style typed wrappers delegating to the generated core.
// Regenerate after `npm run sync:core` with `npm run gen:namespaces`.

import {
  AddressesApi,
  CardsApi,
  CheckoutApi,
  CouponsApi,
  CustomersApi,
  FinanceApi,
  ProductsApi,
  ProductsVariantsApi,
  ReceivablesApi,
  SimulatorsApi,
  SubscriptionsApi,
  TransactionsApi,
  UtilsApi,
  WalletsApi,
  WebhooksApi,
  WithdrawalsApi,
} from './generated/apis';
import { AutoPager, type PaginateParams } from './pagination';

export class AddressesNamespace {
  constructor(private readonly api: AddressesApi) {}

  /** `createAddress` */
  createAddress(body: NonNullable<Parameters<AddressesApi['createAddress']>[0]>['createAddressRequest'], init?: Parameters<AddressesApi['createAddress']>[1]): ReturnType<AddressesApi['createAddress']> {
    return this.api.createAddress({ createAddressRequest: body }, init);
  }

  /** `deleteAddress` */
  deleteAddress(id: string, init?: Parameters<AddressesApi['deleteAddress']>[1]): ReturnType<AddressesApi['deleteAddress']> {
    return this.api.deleteAddress({ addressId: id }, init);
  }

  /** `getAddress` */
  retrieveAddress(id: string, init?: Parameters<AddressesApi['getAddress']>[1]): ReturnType<AddressesApi['getAddress']> {
    return this.api.getAddress({ addressId: id }, init);
  }

  /** `listAddresses` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  list(params?: Parameters<AddressesApi['listAddresses']>[0], init?: Parameters<AddressesApi['listAddresses']>[1]): AutoPager<NonNullable<Awaited<ReturnType<AddressesApi['listAddresses']>>['data']>[number], Awaited<ReturnType<AddressesApi['listAddresses']>>> {
    return new AutoPager((p) => this.api.listAddresses(p as Parameters<AddressesApi['listAddresses']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** `updateAddress` */
  updateAddress(id: string, body: NonNullable<Parameters<AddressesApi['updateAddress']>[0]>['updateAddressRequest'], init?: Parameters<AddressesApi['updateAddress']>[1]): ReturnType<AddressesApi['updateAddress']> {
    return this.api.updateAddress({ addressId: id, updateAddressRequest: body }, init);
  }

  /** `updateAddressPatch` */
  updateAddressPatch(id: string, body: NonNullable<Parameters<AddressesApi['updateAddressPatch']>[0]>['updateAddressRequest'], init?: Parameters<AddressesApi['updateAddressPatch']>[1]): ReturnType<AddressesApi['updateAddressPatch']> {
    return this.api.updateAddressPatch({ addressId: id, updateAddressRequest: body }, init);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): AddressesApi {
    return this.api;
  }
}

export class CardsNamespace {
  constructor(private readonly api: CardsApi) {}

  /** `createCard` */
  create(body: NonNullable<Parameters<CardsApi['createCard']>[0]>['createCardRequest'], init?: Parameters<CardsApi['createCard']>[1]): ReturnType<CardsApi['createCard']> {
    return this.api.createCard({ createCardRequest: body }, init);
  }

  /** `deleteCard` */
  delete(id: string, init?: Parameters<CardsApi['deleteCard']>[1]): ReturnType<CardsApi['deleteCard']> {
    return this.api.deleteCard({ cardId: id }, init);
  }

  /** `getCard` */
  retrieve(id: string, init?: Parameters<CardsApi['getCard']>[1]): ReturnType<CardsApi['getCard']> {
    return this.api.getCard({ cardId: id }, init);
  }

  /** `listCards` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  list(params?: Parameters<CardsApi['listCards']>[0], init?: Parameters<CardsApi['listCards']>[1]): AutoPager<NonNullable<Awaited<ReturnType<CardsApi['listCards']>>['data']>[number], Awaited<ReturnType<CardsApi['listCards']>>> {
    return new AutoPager((p) => this.api.listCards(p as Parameters<CardsApi['listCards']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): CardsApi {
    return this.api;
  }
}

export class CheckoutNamespace {
  constructor(private readonly api: CheckoutApi) {}

  /** `createCheckoutPaymentLink` */
  createPaymentLink(body: NonNullable<Parameters<CheckoutApi['createCheckoutPaymentLink']>[0]>['createCheckoutPaymentLinkRequest'], init?: Parameters<CheckoutApi['createCheckoutPaymentLink']>[1]): ReturnType<CheckoutApi['createCheckoutPaymentLink']> {
    return this.api.createCheckoutPaymentLink({ createCheckoutPaymentLinkRequest: body }, init);
  }

  /** `createCheckoutSession` */
  createSession(body: NonNullable<Parameters<CheckoutApi['createCheckoutSession']>[0]>['createCheckoutSessionRequest'], init?: Parameters<CheckoutApi['createCheckoutSession']>[1]): ReturnType<CheckoutApi['createCheckoutSession']> {
    return this.api.createCheckoutSession({ createCheckoutSessionRequest: body }, init);
  }

  /** `deleteCheckoutPaymentLink` */
  deletePaymentLink(id: string, init?: Parameters<CheckoutApi['deleteCheckoutPaymentLink']>[1]): ReturnType<CheckoutApi['deleteCheckoutPaymentLink']> {
    return this.api.deleteCheckoutPaymentLink({ paymentLinkId: id }, init);
  }

  /** `deleteCheckoutSession` */
  deleteSession(id: string, init?: Parameters<CheckoutApi['deleteCheckoutSession']>[1]): ReturnType<CheckoutApi['deleteCheckoutSession']> {
    return this.api.deleteCheckoutSession({ sessionId: id }, init);
  }

  /** `getCheckoutPaymentLink` */
  retrievePaymentLink(id: string, init?: Parameters<CheckoutApi['getCheckoutPaymentLink']>[1]): ReturnType<CheckoutApi['getCheckoutPaymentLink']> {
    return this.api.getCheckoutPaymentLink({ paymentLinkId: id }, init);
  }

  /** `getCheckoutSession` */
  retrieveSession(id: string, init?: Parameters<CheckoutApi['getCheckoutSession']>[1]): ReturnType<CheckoutApi['getCheckoutSession']> {
    return this.api.getCheckoutSession({ sessionId: id }, init);
  }

  /** `listCheckoutPaymentLinks` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  listPaymentLinks(params?: Parameters<CheckoutApi['listCheckoutPaymentLinks']>[0], init?: Parameters<CheckoutApi['listCheckoutPaymentLinks']>[1]): AutoPager<NonNullable<Awaited<ReturnType<CheckoutApi['listCheckoutPaymentLinks']>>['data']>[number], Awaited<ReturnType<CheckoutApi['listCheckoutPaymentLinks']>>> {
    return new AutoPager((p) => this.api.listCheckoutPaymentLinks(p as Parameters<CheckoutApi['listCheckoutPaymentLinks']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** `listCheckoutSessions` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  listSessions(params?: Parameters<CheckoutApi['listCheckoutSessions']>[0], init?: Parameters<CheckoutApi['listCheckoutSessions']>[1]): AutoPager<NonNullable<Awaited<ReturnType<CheckoutApi['listCheckoutSessions']>>['data']>[number], Awaited<ReturnType<CheckoutApi['listCheckoutSessions']>>> {
    return new AutoPager((p) => this.api.listCheckoutSessions(p as Parameters<CheckoutApi['listCheckoutSessions']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** `submitCheckoutPayment` */
  submitPayment(id: string, body: NonNullable<Parameters<CheckoutApi['submitCheckoutPayment']>[0]>['submitCheckoutPaymentRequest'], init?: Parameters<CheckoutApi['submitCheckoutPayment']>[1]): ReturnType<CheckoutApi['submitCheckoutPayment']> {
    return this.api.submitCheckoutPayment({ sessionId: id, submitCheckoutPaymentRequest: body }, init);
  }

  /** `updateCheckoutPaymentLink` */
  updatePaymentLink(id: string, body: NonNullable<Parameters<CheckoutApi['updateCheckoutPaymentLink']>[0]>['updateCheckoutPaymentLinkRequest'], init?: Parameters<CheckoutApi['updateCheckoutPaymentLink']>[1]): ReturnType<CheckoutApi['updateCheckoutPaymentLink']> {
    return this.api.updateCheckoutPaymentLink({ paymentLinkId: id, updateCheckoutPaymentLinkRequest: body }, init);
  }

  /** `updateCheckoutPaymentLinkPatch` */
  updatePaymentLinkPatch(id: string, body: NonNullable<Parameters<CheckoutApi['updateCheckoutPaymentLinkPatch']>[0]>['updateCheckoutPaymentLinkRequest'], init?: Parameters<CheckoutApi['updateCheckoutPaymentLinkPatch']>[1]): ReturnType<CheckoutApi['updateCheckoutPaymentLinkPatch']> {
    return this.api.updateCheckoutPaymentLinkPatch({ paymentLinkId: id, updateCheckoutPaymentLinkRequest: body }, init);
  }

  /** `updateCheckoutSession` */
  updateSession(id: string, body: NonNullable<Parameters<CheckoutApi['updateCheckoutSession']>[0]>['updateCheckoutSessionRequest'], init?: Parameters<CheckoutApi['updateCheckoutSession']>[1]): ReturnType<CheckoutApi['updateCheckoutSession']> {
    return this.api.updateCheckoutSession({ sessionId: id, updateCheckoutSessionRequest: body }, init);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): CheckoutApi {
    return this.api;
  }
}

export class CouponsNamespace {
  constructor(private readonly api: CouponsApi) {}

  /** `createCoupon` */
  create(body: NonNullable<Parameters<CouponsApi['createCoupon']>[0]>['createCouponRequest'], init?: Parameters<CouponsApi['createCoupon']>[1]): ReturnType<CouponsApi['createCoupon']> {
    return this.api.createCoupon({ createCouponRequest: body }, init);
  }

  /** `deleteCoupon` */
  delete(id: string, init?: Parameters<CouponsApi['deleteCoupon']>[1]): ReturnType<CouponsApi['deleteCoupon']> {
    return this.api.deleteCoupon({ couponId: id }, init);
  }

  /** `getCoupon` */
  retrieve(id: string, init?: Parameters<CouponsApi['getCoupon']>[1]): ReturnType<CouponsApi['getCoupon']> {
    return this.api.getCoupon({ couponId: id }, init);
  }

  /** `listCoupons` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  list(params?: Parameters<CouponsApi['listCoupons']>[0], init?: Parameters<CouponsApi['listCoupons']>[1]): AutoPager<NonNullable<Awaited<ReturnType<CouponsApi['listCoupons']>>['data']>[number], Awaited<ReturnType<CouponsApi['listCoupons']>>> {
    return new AutoPager((p) => this.api.listCoupons(p as Parameters<CouponsApi['listCoupons']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** `patchCoupon` */
  patch(id: string, body: NonNullable<Parameters<CouponsApi['patchCoupon']>[0]>['updateCouponRequest'], init?: Parameters<CouponsApi['patchCoupon']>[1]): ReturnType<CouponsApi['patchCoupon']> {
    return this.api.patchCoupon({ couponId: id, updateCouponRequest: body }, init);
  }

  /** `updateCoupon` */
  update(id: string, body: NonNullable<Parameters<CouponsApi['updateCoupon']>[0]>['updateCouponRequest'], init?: Parameters<CouponsApi['updateCoupon']>[1]): ReturnType<CouponsApi['updateCoupon']> {
    return this.api.updateCoupon({ couponId: id, updateCouponRequest: body }, init);
  }

  /** `validateCoupon` */
  validate(body: NonNullable<Parameters<CouponsApi['validateCoupon']>[0]>['validateCouponRequest'], init?: Parameters<CouponsApi['validateCoupon']>[1]): ReturnType<CouponsApi['validateCoupon']> {
    return this.api.validateCoupon({ validateCouponRequest: body }, init);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): CouponsApi {
    return this.api;
  }
}

export class CustomersNamespace {
  constructor(private readonly api: CustomersApi) {}

  /** `createCustomer` */
  create(body: NonNullable<Parameters<CustomersApi['createCustomer']>[0]>['createCustomerRequest'], init?: Parameters<CustomersApi['createCustomer']>[1]): ReturnType<CustomersApi['createCustomer']> {
    return this.api.createCustomer({ createCustomerRequest: body }, init);
  }

  /** `deleteCustomer` */
  delete(id: string, init?: Parameters<CustomersApi['deleteCustomer']>[1]): ReturnType<CustomersApi['deleteCustomer']> {
    return this.api.deleteCustomer({ customerId: id }, init);
  }

  /** `getCustomer` */
  retrieve(id: string, init?: Parameters<CustomersApi['getCustomer']>[1]): ReturnType<CustomersApi['getCustomer']> {
    return this.api.getCustomer({ customerId: id }, init);
  }

  /** `listCustomers` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  list(params?: Parameters<CustomersApi['listCustomers']>[0], init?: Parameters<CustomersApi['listCustomers']>[1]): AutoPager<NonNullable<Awaited<ReturnType<CustomersApi['listCustomers']>>['data']>[number], Awaited<ReturnType<CustomersApi['listCustomers']>>> {
    return new AutoPager((p) => this.api.listCustomers(p as Parameters<CustomersApi['listCustomers']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** `updateCustomer` */
  update(id: string, body: NonNullable<Parameters<CustomersApi['updateCustomer']>[0]>['updateCustomerPutRequest'], init?: Parameters<CustomersApi['updateCustomer']>[1]): ReturnType<CustomersApi['updateCustomer']> {
    return this.api.updateCustomer({ customerId: id, updateCustomerPutRequest: body }, init);
  }

  /** `updateCustomerPut` */
  updatePut(id: string, body: NonNullable<Parameters<CustomersApi['updateCustomerPut']>[0]>['updateCustomerPutRequest'], init?: Parameters<CustomersApi['updateCustomerPut']>[1]): ReturnType<CustomersApi['updateCustomerPut']> {
    return this.api.updateCustomerPut({ customerId: id, updateCustomerPutRequest: body }, init);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): CustomersApi {
    return this.api;
  }
}

export class FinanceNamespace {
  constructor(private readonly api: FinanceApi) {}

  /** `getBalance` */
  retrieveBalance(...args: Parameters<FinanceApi['getBalance']>): ReturnType<FinanceApi['getBalance']> {
    return this.api.getBalance(...args);
  }

  /** `listBalanceHistory` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  listBalanceHistory(params?: Parameters<FinanceApi['listBalanceHistory']>[0], init?: Parameters<FinanceApi['listBalanceHistory']>[1]): AutoPager<NonNullable<Awaited<ReturnType<FinanceApi['listBalanceHistory']>>['data']>[number], Awaited<ReturnType<FinanceApi['listBalanceHistory']>>> {
    return new AutoPager((p) => this.api.listBalanceHistory(p as Parameters<FinanceApi['listBalanceHistory']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): FinanceApi {
    return this.api;
  }
}

export class ProductsNamespace {
  constructor(private readonly api: ProductsApi) {}

  /** `createProduct` */
  create(body: NonNullable<Parameters<ProductsApi['createProduct']>[0]>['createProductRequest'], init?: Parameters<ProductsApi['createProduct']>[1]): ReturnType<ProductsApi['createProduct']> {
    return this.api.createProduct({ createProductRequest: body }, init);
  }

  /** `deleteProduct` */
  delete(id: string, init?: Parameters<ProductsApi['deleteProduct']>[1]): ReturnType<ProductsApi['deleteProduct']> {
    return this.api.deleteProduct({ productId: id }, init);
  }

  /** `getProduct` */
  retrieve(id: string, init?: Parameters<ProductsApi['getProduct']>[1]): ReturnType<ProductsApi['getProduct']> {
    return this.api.getProduct({ productId: id }, init);
  }

  /** `listProducts` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  list(params?: Parameters<ProductsApi['listProducts']>[0], init?: Parameters<ProductsApi['listProducts']>[1]): AutoPager<NonNullable<Awaited<ReturnType<ProductsApi['listProducts']>>['data']>[number], Awaited<ReturnType<ProductsApi['listProducts']>>> {
    return new AutoPager((p) => this.api.listProducts(p as Parameters<ProductsApi['listProducts']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** `updateProduct` */
  update(id: string, body: NonNullable<Parameters<ProductsApi['updateProduct']>[0]>['updateProductPutRequest'], init?: Parameters<ProductsApi['updateProduct']>[1]): ReturnType<ProductsApi['updateProduct']> {
    return this.api.updateProduct({ productId: id, updateProductPutRequest: body }, init);
  }

  /** `updateProductPut` */
  updatePut(id: string, body: NonNullable<Parameters<ProductsApi['updateProductPut']>[0]>['updateProductPutRequest'], init?: Parameters<ProductsApi['updateProductPut']>[1]): ReturnType<ProductsApi['updateProductPut']> {
    return this.api.updateProductPut({ productId: id, updateProductPutRequest: body }, init);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): ProductsApi {
    return this.api;
  }
}

export class ProductsVariantsNamespace {
  constructor(private readonly api: ProductsVariantsApi) {}

  /** `createProductVariant` */
  create(id: string, body: NonNullable<Parameters<ProductsVariantsApi['createProductVariant']>[0]>['createProductRequestVariantsInner'], init?: Parameters<ProductsVariantsApi['createProductVariant']>[1]): ReturnType<ProductsVariantsApi['createProductVariant']> {
    return this.api.createProductVariant({ productId: id, createProductRequestVariantsInner: body }, init);
  }

  /** `deleteProductVariant` */
  delete(...args: Parameters<ProductsVariantsApi['deleteProductVariant']>): ReturnType<ProductsVariantsApi['deleteProductVariant']> {
    return this.api.deleteProductVariant(...args);
  }

  /** `deleteVariant` */
  deleteVariant(id: string, init?: Parameters<ProductsVariantsApi['deleteVariant']>[1]): ReturnType<ProductsVariantsApi['deleteVariant']> {
    return this.api.deleteVariant({ variantId: id }, init);
  }

  /** `getProductVariant` */
  retrieve(...args: Parameters<ProductsVariantsApi['getProductVariant']>): ReturnType<ProductsVariantsApi['getProductVariant']> {
    return this.api.getProductVariant(...args);
  }

  /** `getVariant` */
  getVariant(id: string, init?: Parameters<ProductsVariantsApi['getVariant']>[1]): ReturnType<ProductsVariantsApi['getVariant']> {
    return this.api.getVariant({ variantId: id }, init);
  }

  /** `listAllVariants` */
  listAll(...args: Parameters<ProductsVariantsApi['listAllVariants']>): ReturnType<ProductsVariantsApi['listAllVariants']> {
    return this.api.listAllVariants(...args);
  }

  /** `listProductVariants` */
  list(...args: Parameters<ProductsVariantsApi['listProductVariants']>): ReturnType<ProductsVariantsApi['listProductVariants']> {
    return this.api.listProductVariants(...args);
  }

  /** `updateProductVariant` */
  update(...args: Parameters<ProductsVariantsApi['updateProductVariant']>): ReturnType<ProductsVariantsApi['updateProductVariant']> {
    return this.api.updateProductVariant(...args);
  }

  /** `updateProductVariantPut` */
  updatePut(...args: Parameters<ProductsVariantsApi['updateProductVariantPut']>): ReturnType<ProductsVariantsApi['updateProductVariantPut']> {
    return this.api.updateProductVariantPut(...args);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): ProductsVariantsApi {
    return this.api;
  }
}

export class ReceivablesNamespace {
  constructor(private readonly api: ReceivablesApi) {}

  /** `getReceivable` */
  retrieve(id: string, init?: Parameters<ReceivablesApi['getReceivable']>[1]): ReturnType<ReceivablesApi['getReceivable']> {
    return this.api.getReceivable({ receivableId: id }, init);
  }

  /** `listReceivables` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  list(params?: Parameters<ReceivablesApi['listReceivables']>[0], init?: Parameters<ReceivablesApi['listReceivables']>[1]): AutoPager<NonNullable<Awaited<ReturnType<ReceivablesApi['listReceivables']>>['data']>[number], Awaited<ReturnType<ReceivablesApi['listReceivables']>>> {
    return new AutoPager((p) => this.api.listReceivables(p as Parameters<ReceivablesApi['listReceivables']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): ReceivablesApi {
    return this.api;
  }
}

export class SimulatorsNamespace {
  constructor(private readonly api: SimulatorsApi) {}

  /** `simulateInstallment` */
  simulateInstallment(...args: Parameters<SimulatorsApi['simulateInstallment']>): ReturnType<SimulatorsApi['simulateInstallment']> {
    return this.api.simulateInstallment(...args);
  }

  /** `simulateInstallments` */
  simulateInstallments(...args: Parameters<SimulatorsApi['simulateInstallments']>): ReturnType<SimulatorsApi['simulateInstallments']> {
    return this.api.simulateInstallments(...args);
  }

  /** `simulatePaymentMethods` */
  simulatePaymentMethods(...args: Parameters<SimulatorsApi['simulatePaymentMethods']>): ReturnType<SimulatorsApi['simulatePaymentMethods']> {
    return this.api.simulatePaymentMethods(...args);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): SimulatorsApi {
    return this.api;
  }
}

export class SubscriptionsNamespace {
  constructor(private readonly api: SubscriptionsApi) {}

  /** `addSubscriptionItem` */
  addItem(id: string, body: NonNullable<Parameters<SubscriptionsApi['addSubscriptionItem']>[0]>['addSubscriptionItemRequest'], init?: Parameters<SubscriptionsApi['addSubscriptionItem']>[1]): ReturnType<SubscriptionsApi['addSubscriptionItem']> {
    return this.api.addSubscriptionItem({ subscriptionId: id, addSubscriptionItemRequest: body }, init);
  }

  /** `addSubscriptionSplit` */
  addSplit(id: string, body: NonNullable<Parameters<SubscriptionsApi['addSubscriptionSplit']>[0]>['createSubscriptionRequestSplitsInner'], init?: Parameters<SubscriptionsApi['addSubscriptionSplit']>[1]): ReturnType<SubscriptionsApi['addSubscriptionSplit']> {
    return this.api.addSubscriptionSplit({ subscriptionId: id, createSubscriptionRequestSplitsInner: body }, init);
  }

  /** `addSubscriptionThreshold` */
  addThreshold(id: string, body: NonNullable<Parameters<SubscriptionsApi['addSubscriptionThreshold']>[0]>['addSubscriptionThresholdRequest'], init?: Parameters<SubscriptionsApi['addSubscriptionThreshold']>[1]): ReturnType<SubscriptionsApi['addSubscriptionThreshold']> {
    return this.api.addSubscriptionThreshold({ subscriptionId: id, addSubscriptionThresholdRequest: body }, init);
  }

  /** `cancelSubscription` */
  cancel(id: string, body: NonNullable<Parameters<SubscriptionsApi['cancelSubscription']>[0]>['cancelSubscriptionRequest'], init?: Parameters<SubscriptionsApi['cancelSubscription']>[1]): ReturnType<SubscriptionsApi['cancelSubscription']> {
    return this.api.cancelSubscription({ subscriptionId: id, cancelSubscriptionRequest: body }, init);
  }

  /** `createSubscription` */
  create(body: NonNullable<Parameters<SubscriptionsApi['createSubscription']>[0]>['createSubscriptionRequest'], init?: Parameters<SubscriptionsApi['createSubscription']>[1]): ReturnType<SubscriptionsApi['createSubscription']> {
    return this.api.createSubscription({ createSubscriptionRequest: body }, init);
  }

  /** `getSubscription` */
  retrieve(id: string, init?: Parameters<SubscriptionsApi['getSubscription']>[1]): ReturnType<SubscriptionsApi['getSubscription']> {
    return this.api.getSubscription({ subscriptionId: id }, init);
  }

  /** `getSubscriptionCycle` */
  retrieveCycle(...args: Parameters<SubscriptionsApi['getSubscriptionCycle']>): ReturnType<SubscriptionsApi['getSubscriptionCycle']> {
    return this.api.getSubscriptionCycle(...args);
  }

  /** `getSubscriptionCycleUsage` */
  retrieveCycleUsage(...args: Parameters<SubscriptionsApi['getSubscriptionCycleUsage']>): ReturnType<SubscriptionsApi['getSubscriptionCycleUsage']> {
    return this.api.getSubscriptionCycleUsage(...args);
  }

  /** `getSubscriptionItem` */
  retrieveItem(...args: Parameters<SubscriptionsApi['getSubscriptionItem']>): ReturnType<SubscriptionsApi['getSubscriptionItem']> {
    return this.api.getSubscriptionItem(...args);
  }

  /** `getSubscriptionSplit` */
  retrieveSplit(...args: Parameters<SubscriptionsApi['getSubscriptionSplit']>): ReturnType<SubscriptionsApi['getSubscriptionSplit']> {
    return this.api.getSubscriptionSplit(...args);
  }

  /** `listSubscriptionCycles` */
  listCycles(...args: Parameters<SubscriptionsApi['listSubscriptionCycles']>): ReturnType<SubscriptionsApi['listSubscriptionCycles']> {
    return this.api.listSubscriptionCycles(...args);
  }

  /** `listSubscriptionItems` */
  listItems(...args: Parameters<SubscriptionsApi['listSubscriptionItems']>): ReturnType<SubscriptionsApi['listSubscriptionItems']> {
    return this.api.listSubscriptionItems(...args);
  }

  /** `listSubscriptionSplits` */
  listSplits(...args: Parameters<SubscriptionsApi['listSubscriptionSplits']>): ReturnType<SubscriptionsApi['listSubscriptionSplits']> {
    return this.api.listSubscriptionSplits(...args);
  }

  /** `listSubscriptionThresholds` */
  listThresholds(...args: Parameters<SubscriptionsApi['listSubscriptionThresholds']>): ReturnType<SubscriptionsApi['listSubscriptionThresholds']> {
    return this.api.listSubscriptionThresholds(...args);
  }

  /** `listSubscriptionUsage` */
  listUsage(...args: Parameters<SubscriptionsApi['listSubscriptionUsage']>): ReturnType<SubscriptionsApi['listSubscriptionUsage']> {
    return this.api.listSubscriptionUsage(...args);
  }

  /** `listSubscriptions` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  list(params?: Parameters<SubscriptionsApi['listSubscriptions']>[0], init?: Parameters<SubscriptionsApi['listSubscriptions']>[1]): AutoPager<NonNullable<Awaited<ReturnType<SubscriptionsApi['listSubscriptions']>>['data']>[number], Awaited<ReturnType<SubscriptionsApi['listSubscriptions']>>> {
    return new AutoPager((p) => this.api.listSubscriptions(p as Parameters<SubscriptionsApi['listSubscriptions']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** `pauseSubscription` */
  pause(id: string, init?: Parameters<SubscriptionsApi['pauseSubscription']>[1]): ReturnType<SubscriptionsApi['pauseSubscription']> {
    return this.api.pauseSubscription({ subscriptionId: id }, init);
  }

  /** `recordSubscriptionUsage` */
  recordUsage(...args: Parameters<SubscriptionsApi['recordSubscriptionUsage']>): ReturnType<SubscriptionsApi['recordSubscriptionUsage']> {
    return this.api.recordSubscriptionUsage(...args);
  }

  /** `removeSubscriptionItem` */
  removeItem(...args: Parameters<SubscriptionsApi['removeSubscriptionItem']>): ReturnType<SubscriptionsApi['removeSubscriptionItem']> {
    return this.api.removeSubscriptionItem(...args);
  }

  /** `removeSubscriptionSplit` */
  removeSplit(...args: Parameters<SubscriptionsApi['removeSubscriptionSplit']>): ReturnType<SubscriptionsApi['removeSubscriptionSplit']> {
    return this.api.removeSubscriptionSplit(...args);
  }

  /** `removeSubscriptionThreshold` */
  removeThreshold(...args: Parameters<SubscriptionsApi['removeSubscriptionThreshold']>): ReturnType<SubscriptionsApi['removeSubscriptionThreshold']> {
    return this.api.removeSubscriptionThreshold(...args);
  }

  /** `renewSubscriptionCycle` */
  renewCycle(id: string, init?: Parameters<SubscriptionsApi['renewSubscriptionCycle']>[1]): ReturnType<SubscriptionsApi['renewSubscriptionCycle']> {
    return this.api.renewSubscriptionCycle({ subscriptionId: id }, init);
  }

  /** `resumeSubscription` */
  resume(id: string, init?: Parameters<SubscriptionsApi['resumeSubscription']>[1]): ReturnType<SubscriptionsApi['resumeSubscription']> {
    return this.api.resumeSubscription({ subscriptionId: id }, init);
  }

  /** `updateSubscriptionItem` */
  updateItem(...args: Parameters<SubscriptionsApi['updateSubscriptionItem']>): ReturnType<SubscriptionsApi['updateSubscriptionItem']> {
    return this.api.updateSubscriptionItem(...args);
  }

  /** `updateSubscriptionItemPut` */
  updateItemPut(...args: Parameters<SubscriptionsApi['updateSubscriptionItemPut']>): ReturnType<SubscriptionsApi['updateSubscriptionItemPut']> {
    return this.api.updateSubscriptionItemPut(...args);
  }

  /** `updateSubscriptionSplit` */
  updateSplit(...args: Parameters<SubscriptionsApi['updateSubscriptionSplit']>): ReturnType<SubscriptionsApi['updateSubscriptionSplit']> {
    return this.api.updateSubscriptionSplit(...args);
  }

  /** `updateSubscriptionSplitPut` */
  updateSplitPut(...args: Parameters<SubscriptionsApi['updateSubscriptionSplitPut']>): ReturnType<SubscriptionsApi['updateSubscriptionSplitPut']> {
    return this.api.updateSubscriptionSplitPut(...args);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): SubscriptionsApi {
    return this.api;
  }
}

export class TransactionsNamespace {
  constructor(private readonly api: TransactionsApi) {}

  /** `captureTransaction` */
  capture(id: string, body: NonNullable<Parameters<TransactionsApi['captureTransaction']>[0]>['captureTransactionRequest'], init?: Parameters<TransactionsApi['captureTransaction']>[1]): ReturnType<TransactionsApi['captureTransaction']> {
    return this.api.captureTransaction({ transactionId: id, captureTransactionRequest: body }, init);
  }

  /** `createTransaction` */
  create(body: NonNullable<Parameters<TransactionsApi['createTransaction']>[0]>['createTransactionRequest'], init?: Parameters<TransactionsApi['createTransaction']>[1]): ReturnType<TransactionsApi['createTransaction']> {
    return this.api.createTransaction({ createTransactionRequest: body }, init);
  }

  /** `getTransaction` */
  retrieve(id: string, init?: Parameters<TransactionsApi['getTransaction']>[1]): ReturnType<TransactionsApi['getTransaction']> {
    return this.api.getTransaction({ transactionId: id }, init);
  }

  /** `listTransactions` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  list(params?: Parameters<TransactionsApi['listTransactions']>[0], init?: Parameters<TransactionsApi['listTransactions']>[1]): AutoPager<NonNullable<Awaited<ReturnType<TransactionsApi['listTransactions']>>['data']>[number], Awaited<ReturnType<TransactionsApi['listTransactions']>>> {
    return new AutoPager((p) => this.api.listTransactions(p as Parameters<TransactionsApi['listTransactions']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** `refundTransaction` */
  refund(id: string, body: NonNullable<Parameters<TransactionsApi['refundTransaction']>[0]>['refundTransactionRequest'], init?: Parameters<TransactionsApi['refundTransaction']>[1]): ReturnType<TransactionsApi['refundTransaction']> {
    return this.api.refundTransaction({ transactionId: id, refundTransactionRequest: body }, init);
  }

  /** `submitTransactionDispute` */
  submitDispute(id: string, body: NonNullable<Parameters<TransactionsApi['submitTransactionDispute']>[0]>['submitTransactionDisputeRequest'], init?: Parameters<TransactionsApi['submitTransactionDispute']>[1]): ReturnType<TransactionsApi['submitTransactionDispute']> {
    return this.api.submitTransactionDispute({ transactionId: id, submitTransactionDisputeRequest: body }, init);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): TransactionsApi {
    return this.api;
  }
}

export class UtilsNamespace {
  constructor(private readonly api: UtilsApi) {}

  /** `utilsCardBinValidation` */
  utilsCardBinValidation(...args: Parameters<UtilsApi['utilsCardBinValidation']>): ReturnType<UtilsApi['utilsCardBinValidation']> {
    return this.api.utilsCardBinValidation(...args);
  }

  /** `utilsCompanyTypes` */
  utilsCompanyTypes(...args: Parameters<UtilsApi['utilsCompanyTypes']>): ReturnType<UtilsApi['utilsCompanyTypes']> {
    return this.api.utilsCompanyTypes(...args);
  }

  /** `utilsCorporateDocumentCheck` */
  utilsCorporateDocumentCheck(...args: Parameters<UtilsApi['utilsCorporateDocumentCheck']>): ReturnType<UtilsApi['utilsCorporateDocumentCheck']> {
    return this.api.utilsCorporateDocumentCheck(...args);
  }

  /** `utilsMetadata` */
  utilsMetadata(...args: Parameters<UtilsApi['utilsMetadata']>): ReturnType<UtilsApi['utilsMetadata']> {
    return this.api.utilsMetadata(...args);
  }

  /** `utilsPostcodeValidation` */
  utilsPostcodeValidation(...args: Parameters<UtilsApi['utilsPostcodeValidation']>): ReturnType<UtilsApi['utilsPostcodeValidation']> {
    return this.api.utilsPostcodeValidation(...args);
  }

  /** `utilsRolesOfUser` */
  utilsRolesOfUser(...args: Parameters<UtilsApi['utilsRolesOfUser']>): ReturnType<UtilsApi['utilsRolesOfUser']> {
    return this.api.utilsRolesOfUser(...args);
  }

  /** `utilsRulesOfRecurrencies` */
  utilsRulesOfRecurrencies(...args: Parameters<UtilsApi['utilsRulesOfRecurrencies']>): ReturnType<UtilsApi['utilsRulesOfRecurrencies']> {
    return this.api.utilsRulesOfRecurrencies(...args);
  }

  /** `utilsTypesOfBankAccounts` */
  utilsTypesOfBankAccounts(...args: Parameters<UtilsApi['utilsTypesOfBankAccounts']>): ReturnType<UtilsApi['utilsTypesOfBankAccounts']> {
    return this.api.utilsTypesOfBankAccounts(...args);
  }

  /** `utilsTypesOfCompany` */
  utilsTypesOfCompany(...args: Parameters<UtilsApi['utilsTypesOfCompany']>): ReturnType<UtilsApi['utilsTypesOfCompany']> {
    return this.api.utilsTypesOfCompany(...args);
  }

  /** `utilsTypesOfRefund` */
  utilsTypesOfRefund(...args: Parameters<UtilsApi['utilsTypesOfRefund']>): ReturnType<UtilsApi['utilsTypesOfRefund']> {
    return this.api.utilsTypesOfRefund(...args);
  }

  /** `utilsTypesOfWebhooks` */
  utilsTypesOfWebhooks(...args: Parameters<UtilsApi['utilsTypesOfWebhooks']>): ReturnType<UtilsApi['utilsTypesOfWebhooks']> {
    return this.api.utilsTypesOfWebhooks(...args);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): UtilsApi {
    return this.api;
  }
}

export class WalletsNamespace {
  constructor(private readonly api: WalletsApi) {}

  /** `createWallet` */
  create(body: NonNullable<Parameters<WalletsApi['createWallet']>[0]>['createWalletRequest'], init?: Parameters<WalletsApi['createWallet']>[1]): ReturnType<WalletsApi['createWallet']> {
    return this.api.createWallet({ createWalletRequest: body }, init);
  }

  /** `deleteWallet` */
  delete(id: string, init?: Parameters<WalletsApi['deleteWallet']>[1]): ReturnType<WalletsApi['deleteWallet']> {
    return this.api.deleteWallet({ walletId: id }, init);
  }

  /** `getWallet` */
  retrieve(id: string, init?: Parameters<WalletsApi['getWallet']>[1]): ReturnType<WalletsApi['getWallet']> {
    return this.api.getWallet({ walletId: id }, init);
  }

  /** `listWallets` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  list(params?: Parameters<WalletsApi['listWallets']>[0], init?: Parameters<WalletsApi['listWallets']>[1]): AutoPager<NonNullable<Awaited<ReturnType<WalletsApi['listWallets']>>['data']>[number], Awaited<ReturnType<WalletsApi['listWallets']>>> {
    return new AutoPager((p) => this.api.listWallets(p as Parameters<WalletsApi['listWallets']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): WalletsApi {
    return this.api;
  }
}

export class WebhooksNamespace {
  constructor(private readonly api: WebhooksApi) {}

  /** `createWebhookEndpoint` */
  createEndpoint(body: NonNullable<Parameters<WebhooksApi['createWebhookEndpoint']>[0]>['createWebhookEndpointRequest'], init?: Parameters<WebhooksApi['createWebhookEndpoint']>[1]): ReturnType<WebhooksApi['createWebhookEndpoint']> {
    return this.api.createWebhookEndpoint({ createWebhookEndpointRequest: body }, init);
  }

  /** `deleteWebhookEndpoint` */
  deleteEndpoint(...args: Parameters<WebhooksApi['deleteWebhookEndpoint']>): ReturnType<WebhooksApi['deleteWebhookEndpoint']> {
    return this.api.deleteWebhookEndpoint(...args);
  }

  /** `getWebhookEndpoint` */
  retrieveEndpoint(...args: Parameters<WebhooksApi['getWebhookEndpoint']>): ReturnType<WebhooksApi['getWebhookEndpoint']> {
    return this.api.getWebhookEndpoint(...args);
  }

  /** `getWebhookEvent` */
  retrieveEvent(id: string, init?: Parameters<WebhooksApi['getWebhookEvent']>[1]): ReturnType<WebhooksApi['getWebhookEvent']> {
    return this.api.getWebhookEvent({ eventId: id }, init);
  }

  /** `listWebhookDispatches` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  listDispatches(params?: Parameters<WebhooksApi['listWebhookDispatches']>[0], init?: Parameters<WebhooksApi['listWebhookDispatches']>[1]): AutoPager<NonNullable<Awaited<ReturnType<WebhooksApi['listWebhookDispatches']>>['data']>[number], Awaited<ReturnType<WebhooksApi['listWebhookDispatches']>>> {
    return new AutoPager((p) => this.api.listWebhookDispatches(p as Parameters<WebhooksApi['listWebhookDispatches']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** `listWebhookEndpoints` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  listEndpoints(params?: Parameters<WebhooksApi['listWebhookEndpoints']>[0], init?: Parameters<WebhooksApi['listWebhookEndpoints']>[1]): AutoPager<NonNullable<Awaited<ReturnType<WebhooksApi['listWebhookEndpoints']>>['data']>[number], Awaited<ReturnType<WebhooksApi['listWebhookEndpoints']>>> {
    return new AutoPager((p) => this.api.listWebhookEndpoints(p as Parameters<WebhooksApi['listWebhookEndpoints']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** `listWebhookEvents` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  listEvents(params?: Parameters<WebhooksApi['listWebhookEvents']>[0], init?: Parameters<WebhooksApi['listWebhookEvents']>[1]): AutoPager<NonNullable<Awaited<ReturnType<WebhooksApi['listWebhookEvents']>>['data']>[number], Awaited<ReturnType<WebhooksApi['listWebhookEvents']>>> {
    return new AutoPager((p) => this.api.listWebhookEvents(p as Parameters<WebhooksApi['listWebhookEvents']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** `redispatchWebhook` */
  redispatch(...args: Parameters<WebhooksApi['redispatchWebhook']>): ReturnType<WebhooksApi['redispatchWebhook']> {
    return this.api.redispatchWebhook(...args);
  }

  /** `resendWebhookEvent` */
  resendEvent(id: string, init?: Parameters<WebhooksApi['resendWebhookEvent']>[1]): ReturnType<WebhooksApi['resendWebhookEvent']> {
    return this.api.resendWebhookEvent({ eventId: id }, init);
  }

  /** `rotateWebhookSecret` */
  rotateSecret(...args: Parameters<WebhooksApi['rotateWebhookSecret']>): ReturnType<WebhooksApi['rotateWebhookSecret']> {
    return this.api.rotateWebhookSecret(...args);
  }

  /** `testWebhookEndpoint` */
  testEndpoint(...args: Parameters<WebhooksApi['testWebhookEndpoint']>): ReturnType<WebhooksApi['testWebhookEndpoint']> {
    return this.api.testWebhookEndpoint(...args);
  }

  /** `updateWebhookEndpoint` */
  updateEndpoint(...args: Parameters<WebhooksApi['updateWebhookEndpoint']>): ReturnType<WebhooksApi['updateWebhookEndpoint']> {
    return this.api.updateWebhookEndpoint(...args);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): WebhooksApi {
    return this.api;
  }
}

export class WithdrawalsNamespace {
  constructor(private readonly api: WithdrawalsApi) {}

  /** `createWithdrawal` */
  create(body: NonNullable<Parameters<WithdrawalsApi['createWithdrawal']>[0]>['createWithdrawalRequest'], init?: Parameters<WithdrawalsApi['createWithdrawal']>[1]): ReturnType<WithdrawalsApi['createWithdrawal']> {
    return this.api.createWithdrawal({ createWithdrawalRequest: body }, init);
  }

  /** `getWithdrawal` */
  retrieve(id: string, init?: Parameters<WithdrawalsApi['getWithdrawal']>[1]): ReturnType<WithdrawalsApi['getWithdrawal']> {
    return this.api.getWithdrawal({ withdrawalId: id }, init);
  }

  /** `listWithdrawals` — auto-paginating: `await` for the first page, or `for await` to iterate every item. */
  list(params?: Parameters<WithdrawalsApi['listWithdrawals']>[0], init?: Parameters<WithdrawalsApi['listWithdrawals']>[1]): AutoPager<NonNullable<Awaited<ReturnType<WithdrawalsApi['listWithdrawals']>>['data']>[number], Awaited<ReturnType<WithdrawalsApi['listWithdrawals']>>> {
    return new AutoPager((p) => this.api.listWithdrawals(p as Parameters<WithdrawalsApi['listWithdrawals']>[0], init), (params ?? {}) as PaginateParams);
  }

  /** Escape hatch: the underlying generated API (all `operationId` methods). */
  get raw(): WithdrawalsApi {
    return this.api;
  }
}
