/* eslint-disable */
// GENERATED by scripts/gen-webhook-events.mjs — DO NOT EDIT.
// Typed webhook Event Catalog derived from the spec's authoritative event enum
// (`CreateWebhookEndpointRequestEventsEnum`). Regenerate after `npm run sync:core`
// with `npm run gen:webhook-events`.

import type {
  CreateCheckoutSession201Response,
  GetCustomer200Response,
  GetCustomer200ResponseAddressesInner,
  GetCustomer200ResponseCardsInner,
  GetTransaction200Response,
  ListReceivables200ResponseDataInner,
  ListSubscriptions200ResponseDataInner,
  ListWallets200ResponseDataInner,
  ListWebhookEndpoints200ResponseDataInner,
  ListWithdrawals200ResponseDataInner,
} from './generated/models';

/**
 * Every webhook event type Selectwin can deliver — the authoritative catalog,
 * exactly the values a webhook endpoint's `events[]` accepts.
 */
export const WEBHOOK_EVENT_TYPES = [
  'transaction.created',
  'transaction.pending',
  'transaction.failed',
  'transaction.approved',
  'transaction.canceled',
  'transaction.chargeback',
  'transaction.refunded',
  'transaction.fraud-review',
  'transaction.pre-authorized',
  'transaction.unauthorized',
  'transaction.awaiting',
  'transaction.dispute',
  'customer.created',
  'customer.updated',
  'customer.deleted',
  'customer.address.created',
  'customer.address.updated',
  'customer.address.deleted',
  'card.created',
  'card.updated',
  'card.deleted',
  'card.expired',
  'subscription.created',
  'subscription.pending',
  'subscription.active',
  'subscription.canceled',
  'subscription.pastdue',
  'subscription.unpaid',
  'subscription.trialing',
  'subscription.paused',
  'subscription.updated',
  'receivable.created',
  'receivable.pending',
  'receivable.paid',
  'receivable.canceled',
  'receivable.chargeback',
  'receivable.refunded',
  'receivable.dispute',
  'receivable.scheduled',
  'receivable.fraud-hold',
  'wallet.created',
  'wallet.deleted',
  'wallet.pending',
  'wallet.disabled',
  'wallet.enabled',
  'seller.created',
  'seller.updated',
  'seller.analyzing',
  'seller.approved',
  'seller.refused',
  'seller.blocked',
  'seller.disabled',
  'seller.reinstated',
  'withdrawal.created',
  'withdrawal.pending',
  'withdrawal.confirmed',
  'withdrawal.canceled',
  'withdrawal.refused',
  'withdrawal.processing',
  'withdrawal.analysis',
  'webhook.created',
  'webhook.updated',
  'webhook.deleted',
  'webhook.disabled',
  'checkout.session.created',
  'checkout.session.updated',
  'checkout.session.abandoned',
  'checkout.session.recovered',
  'checkout.session.reactivated',
  'checkout.session.expired',
  'checkout.session.completed',
  'webhook.ping',
] as const;

/** Union of every `resource.action` webhook event type. */
export type WebhookEventType = (typeof WEBHOOK_EVENT_TYPES)[number];

/** Runtime guard: is `value` one of the known webhook event types? */
export function isWebhookEventType(value: unknown): value is WebhookEventType {
  return typeof value === 'string' && (WEBHOOK_EVENT_TYPES as readonly string[]).includes(value);
}

/** `transaction.*` event types. */
export type TransactionEventType = 'transaction.created' | 'transaction.pending' | 'transaction.failed' | 'transaction.approved' | 'transaction.canceled' | 'transaction.chargeback' | 'transaction.refunded' | 'transaction.fraud-review' | 'transaction.pre-authorized' | 'transaction.unauthorized' | 'transaction.awaiting' | 'transaction.dispute';

/** `customer.*` event types. */
export type CustomerEventType = 'customer.created' | 'customer.updated' | 'customer.deleted' | 'customer.address.created' | 'customer.address.updated' | 'customer.address.deleted';

/** `card.*` event types. */
export type CardEventType = 'card.created' | 'card.updated' | 'card.deleted' | 'card.expired';

/** `subscription.*` event types. */
export type SubscriptionEventType = 'subscription.created' | 'subscription.pending' | 'subscription.active' | 'subscription.canceled' | 'subscription.pastdue' | 'subscription.unpaid' | 'subscription.trialing' | 'subscription.paused' | 'subscription.updated';

/** `receivable.*` event types. */
export type ReceivableEventType = 'receivable.created' | 'receivable.pending' | 'receivable.paid' | 'receivable.canceled' | 'receivable.chargeback' | 'receivable.refunded' | 'receivable.dispute' | 'receivable.scheduled' | 'receivable.fraud-hold';

/** `wallet.*` event types. */
export type WalletEventType = 'wallet.created' | 'wallet.deleted' | 'wallet.pending' | 'wallet.disabled' | 'wallet.enabled';

/** `seller.*` event types. */
export type SellerEventType = 'seller.created' | 'seller.updated' | 'seller.analyzing' | 'seller.approved' | 'seller.refused' | 'seller.blocked' | 'seller.disabled' | 'seller.reinstated';

/** `withdrawal.*` event types. */
export type WithdrawalEventType = 'withdrawal.created' | 'withdrawal.pending' | 'withdrawal.confirmed' | 'withdrawal.canceled' | 'withdrawal.refused' | 'withdrawal.processing' | 'withdrawal.analysis';

/** `webhook.*` event types. */
export type WebhookEndpointEventType = 'webhook.created' | 'webhook.updated' | 'webhook.deleted' | 'webhook.disabled' | 'webhook.ping';

/** `checkout.*` event types. */
export type CheckoutEventType = 'checkout.session.created' | 'checkout.session.updated' | 'checkout.session.abandoned' | 'checkout.session.recovered' | 'checkout.session.reactivated' | 'checkout.session.expired' | 'checkout.session.completed';

/**
 * Maps each event `type` to the shape of `payload.object` (the resource's read
 * shape). Types without a dedicated resource model resolve to `unknown`.
 */
export interface WebhookEventObjectMap {
  'transaction.created': GetTransaction200Response;
  'transaction.pending': GetTransaction200Response;
  'transaction.failed': GetTransaction200Response;
  'transaction.approved': GetTransaction200Response;
  'transaction.canceled': GetTransaction200Response;
  'transaction.chargeback': GetTransaction200Response;
  'transaction.refunded': GetTransaction200Response;
  'transaction.fraud-review': GetTransaction200Response;
  'transaction.pre-authorized': GetTransaction200Response;
  'transaction.unauthorized': GetTransaction200Response;
  'transaction.awaiting': GetTransaction200Response;
  'transaction.dispute': GetTransaction200Response;
  'customer.created': GetCustomer200Response;
  'customer.updated': GetCustomer200Response;
  'customer.deleted': GetCustomer200Response;
  'customer.address.created': GetCustomer200ResponseAddressesInner;
  'customer.address.updated': GetCustomer200ResponseAddressesInner;
  'customer.address.deleted': GetCustomer200ResponseAddressesInner;
  'card.created': GetCustomer200ResponseCardsInner;
  'card.updated': GetCustomer200ResponseCardsInner;
  'card.deleted': GetCustomer200ResponseCardsInner;
  'card.expired': GetCustomer200ResponseCardsInner;
  'subscription.created': ListSubscriptions200ResponseDataInner;
  'subscription.pending': ListSubscriptions200ResponseDataInner;
  'subscription.active': ListSubscriptions200ResponseDataInner;
  'subscription.canceled': ListSubscriptions200ResponseDataInner;
  'subscription.pastdue': ListSubscriptions200ResponseDataInner;
  'subscription.unpaid': ListSubscriptions200ResponseDataInner;
  'subscription.trialing': ListSubscriptions200ResponseDataInner;
  'subscription.paused': ListSubscriptions200ResponseDataInner;
  'subscription.updated': ListSubscriptions200ResponseDataInner;
  'receivable.created': ListReceivables200ResponseDataInner;
  'receivable.pending': ListReceivables200ResponseDataInner;
  'receivable.paid': ListReceivables200ResponseDataInner;
  'receivable.canceled': ListReceivables200ResponseDataInner;
  'receivable.chargeback': ListReceivables200ResponseDataInner;
  'receivable.refunded': ListReceivables200ResponseDataInner;
  'receivable.dispute': ListReceivables200ResponseDataInner;
  'receivable.scheduled': ListReceivables200ResponseDataInner;
  'receivable.fraud-hold': ListReceivables200ResponseDataInner;
  'wallet.created': ListWallets200ResponseDataInner;
  'wallet.deleted': ListWallets200ResponseDataInner;
  'wallet.pending': ListWallets200ResponseDataInner;
  'wallet.disabled': ListWallets200ResponseDataInner;
  'wallet.enabled': ListWallets200ResponseDataInner;
  'seller.created': unknown;
  'seller.updated': unknown;
  'seller.analyzing': unknown;
  'seller.approved': unknown;
  'seller.refused': unknown;
  'seller.blocked': unknown;
  'seller.disabled': unknown;
  'seller.reinstated': unknown;
  'withdrawal.created': ListWithdrawals200ResponseDataInner;
  'withdrawal.pending': ListWithdrawals200ResponseDataInner;
  'withdrawal.confirmed': ListWithdrawals200ResponseDataInner;
  'withdrawal.canceled': ListWithdrawals200ResponseDataInner;
  'withdrawal.refused': ListWithdrawals200ResponseDataInner;
  'withdrawal.processing': ListWithdrawals200ResponseDataInner;
  'withdrawal.analysis': ListWithdrawals200ResponseDataInner;
  'webhook.created': ListWebhookEndpoints200ResponseDataInner;
  'webhook.updated': ListWebhookEndpoints200ResponseDataInner;
  'webhook.deleted': ListWebhookEndpoints200ResponseDataInner;
  'webhook.disabled': ListWebhookEndpoints200ResponseDataInner;
  'checkout.session.created': CreateCheckoutSession201Response;
  'checkout.session.updated': CreateCheckoutSession201Response;
  'checkout.session.abandoned': CreateCheckoutSession201Response;
  'checkout.session.recovered': CreateCheckoutSession201Response;
  'checkout.session.reactivated': CreateCheckoutSession201Response;
  'checkout.session.expired': CreateCheckoutSession201Response;
  'checkout.session.completed': CreateCheckoutSession201Response;
  'webhook.ping': unknown;
}

/** Common envelope fields shared by every delivered webhook event. */
export interface SelectwinEventBase {
  /** Public event id (`wbh_...`). Deduplicate on this. */
  id: string;
  /** Event origin (`automatic` for platform events; `api` for the test ping). */
  source?: string;
  /** Correlation id of the originating request, when available. */
  correlationId?: string | null;
  /** Present only on marketplace fan-out to a parent: the sub-account publicId. */
  account?: string;
  createdAt?: string;
  updatedAt?: string;
  [k: string]: unknown;
}

/** A single, fully-typed webhook event for one specific `type`. */
export interface SelectwinEventOf<T extends WebhookEventType> extends SelectwinEventBase {
  type: T;
  payload: { object: WebhookEventObjectMap[T] };
}

/**
 * Discriminated union over every event type. `switch (event.type)` (or
 * `if (event.type === 'transaction.approved')`) narrows `event.payload.object`
 * to the matching resource shape.
 */
export type SelectwinEventUnion = { [K in WebhookEventType]: SelectwinEventOf<K> }[WebhookEventType];
